steps:
  - name: "gcr.io/cloud-builders/go"
    args:
      - "build"
      - "-o"
      - "bin/goServer"
    env:
      - "GOPATH=golib"
    dir: "server"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "app"
      - "deploy"
      - --project gcp-golang-101
    env:
      - "GOPATH=golib"
    dir: "server"
    timeout: "600s"
